#Program to accept book details and print them
bcode=input("Enter Book Code:")
bno=input("Enter Book No:")
bname=input("Enter Book Name:")
bprice=float(input("Enter Book Price:"))
bpcode=input("Enter Book Print Code:")
print("___________________________________")
print("\t Book details ")
print("___________________________________")
print("Code=",bcode)
print("Number=",bno)
print("Name=",bname)
print("Price=",bprice)
print("Print Code=",bpcode)
print("____________________________________")