#Program without using a function
print("Apple")
print("Mango")
print("Grapes")
print("Orange")
print("Banana")
print("Apple")
print("Mango")
print("Grapes")
print("Orange")
print("Banana")
